name: Build and Publish Npm Pkg to Docker

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

env:
  version: 0

jobs:
  build-publish-npmpkg:
    runs-on: ubuntu-latest
    permissions:
            packages: write
            contents: read
    steps:
      - uses: actions/checkout@v3
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tamilvananb'
      
      - name: Replace the token in npmrc file
        shell: bash
        env: 
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
         sed -i.back "s|NODE_AUTH_TOKEN|${PAT}|g" .npmrc
         
      - name: Get current package version   
        run: echo "version=$(npm show @tamilvananb/nestjs-swagger version)" >> $GITHUB_ENV
        
      - name: Set package version in environment  
        run: npm version ${{env.version}} --no-git-tag-version --allow-same-version
      
      - name: Install dependencies
        run: npm install
      
      - name: Update package version
        run: npm version patch -m "[RELEASE] %s" --no-git-tag-version --allow-same-version
        
      - name: Run unit tests
        run: npm run test:cov
        continue-on-error: true
        
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build_and_publish:
    runs-on: ubuntu-latest
    needs: build-publish-npmpkg
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      
      
      
      - name: Build the Docker image
        run: docker build -t k8stest:latest .
      - name: Tag the Docker image
        run: docker tag k8stest:latest docker.pkg.github.com/tamilvananb/k8stest:latest
      - name: Push the Docker image to the registry
        run: docker push docker.pkg.github.com/tamilvananb/k8stest:latest
